### ISSUE TITLE
Docs: Exmples for Amount field using numberField

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/field#120]
**Is your feature request related to a problem? Please describe.**
I am looking for the numberField to be showcased as amount field say $3.09 or $0.99 (ignore $). Decimal with specific digit after dot.

**Describe the solution you'd like**
I am looking for only examples. As of now I am seeing only integers.

**Describe alternatives you've considered**
As of now I have to use string field with custom zod valiadtion 
**Additional context**

**Comment by MiroslavPetrik** [comment]
Currently there is plain number input, which allows decimals:
![image](https://github.com/form-atoms/field/assets/38855190/114c4fb4-15b4-4f9f-a7e4-ae89a72471a9)

Not sure what you miss. If you need constraint for 2 decimal places, you need to set your input element properties, like pattern, min, max etc
