### ISSUE TITLE
Doc: Need example of conditional schema using get as in userValidateConfig

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/field#126]
**Is your feature request related to a problem? Please describe.**
I am looking for the example for the below overloaded function to get schema dynamically based on some diff atom. 
![Screenshot 2024-05-14 at 8 17 08 AM](https://github.com/form-atoms/field/assets/14316332/32ad780b-a304-4488-9f4c-2526e31838ff)
I checked many test files and stories, didnt find anywhere.  When I tried myself as 
```ts
stringField({
schema : (s, get) => z.min(6).pipe(z.literal(get(someAtom).value))
});
```
Need to know if I am doing something wrong as I see some typescript errors.
**Describe the solution you'd like**
Need example of conditional schema along with optional callback based on diff atom.

**Describe alternatives you've considered**

**Additional context**

**Comment by pgangwani** [comment]
There is type error when using schema function with 2 arguments.

**Comment by MiroslavPetrik** [comment]
> There is type error when using schema function with 2 arguments.

There is an open bug in the typescript: https://github.com/microsoft/TypeScript/issues/54539

I suggest using `// @ts-expect-error overload bug` comment to suppress the type error for now.

**Comment by MiroslavPetrik** [comment]
Also you need one more `get`, to unwrap the `value` which is also atom:

```ts
stringField({
  schema : (s, get) => z.min(6).pipe(z.literal(get(get(someAtom).value)))
});
```

But I believe you will get one more type error, as the pipe + literal type won't extend the `ZodString` which is inside of the `stringField`.
